<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TasksTableSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    $tasks = [
      [
        'project_id'       => 1,
        'assigned_to'      => 1,
        'name'             => 'Công việc của Admin 1',
        'description'      => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
        'percent_complete' => 100,
        'start_date'       => Carbon::create('2020', '01', '06'),
        'due_on'           => Carbon::create('2020', '06', '1'),
        'status_id'        => 2, // xong đúng hạn
        'is_overdue'       => 0,
        'late_completed'   => 0,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '01', '06'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 1,
        'assigned_to'      => 1,
        'name'             => 'Công việc của Admin 2',
        'description'      => '',
        'percent_complete' => 100,
        'start_date'       => Carbon::create('2020', '01', '10'),
        'due_on'           => Carbon::create('2020', '06', '1'),
        'status_id'        => 2, // xong trể hạn
        'is_overdue'       => 0,
        'late_completed'   => 1,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '01', '10'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 1,
        'assigned_to'      => 1,
        'name'             => 'Công việc của Admin 3',
        'description'      => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
        'percent_complete' => 60,
        'start_date'       => Carbon::create('2020', '01', '14'),
        'due_on'           => Carbon::create('2020', '06', '1'),
        'status_id'        => 1, // đang làm
        'is_overdue'       => 0,
        'late_completed'   => 0,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '01', '14'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 1,
        'assigned_to'      => 1,
        'name'             => 'Công việc của Admin 4',
        'description'      => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
        'percent_complete' => 80,
        'start_date'       => Carbon::create('2020', '01', '16'),
        'due_on'           => null,
        'status_id'        => 1, // đang làm + trể hạn
        'is_overdue'       => 0,
        'late_completed'   => 0,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '01', '16'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 1,
        'assigned_to'      => 2,
        'name'             => 'Công việc của Leader 1',
        'description'      => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
        'percent_complete' => 100,
        'start_date'       => Carbon::create('2020', '01', '16'),
        'due_on'           => null,
        'status_id'        => 2,
        'is_overdue'       => 0,
        'late_completed'   => 0,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '01', '16'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 1,
        'assigned_to'      => 2,
        'name'             => 'Công việc của Leader 2',
        'description'      => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
        'percent_complete' => 100,
        'start_date'       => Carbon::create('2020', '01', '16'),
        'due_on'           => null,
        'status_id'        => 2,
        'is_overdue'       => 0,
        'late_completed'   => 1,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '01', '16'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 1,
        'assigned_to'      => 2,
        'name'             => 'Công việc của Leader 3',
        'description'      => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
        'percent_complete' => 20,
        'start_date'       => Carbon::create('2020', '01', '16'),
        'due_on'           => null,
        'status_id'        => 1,
        'is_overdue'       => 0,
        'late_completed'   => 0,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '01', '16'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 1,
        'assigned_to'      => 2,
        'name'             => 'Công việc của Leader 3',
        'description'      => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
        'percent_complete' => 40,
        'start_date'       => Carbon::create('2020', '01', '16'),
        'due_on'           => null,
        'status_id'        => 1,
        'is_overdue'       => 0,
        'late_completed'   => 0,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '01', '16'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 2,
        'assigned_to'      => 4,
        'name'             => 'Công việc của Hạnh 1',
        'description'      => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
        'percent_complete' => 10,
        'start_date'       => Carbon::create('2020', '01', '06'),
        'due_on'           => Carbon::create('2020', '06', '1'),
        'status_id'        => 1,
        'is_overdue'       => 0,
        'late_completed'   => 0,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '01', '06'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 2,
        'assigned_to'      => 4,
        'name'             => 'Công việc của Hạnh 2',
        'description'      => 'Lorem Ipsum is simply dummy text of the printing ',
        'percent_complete' => 100,
        'start_date'       => Carbon::create('2020', '01', '12'),
        'due_on'           => Carbon::create('2020', '06', '1'),
        'status_id'        => 2,
        'is_overdue'       => 0,
        'late_completed'   => 1,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '01', '12'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 2,
        'assigned_to'      => 5,
        'name'             => 'Công việc của Vân 1',
        'description'      => '',
        'percent_complete' => 50,
        'start_date'       => Carbon::create('2020', '01', '09'),
        'due_on'           => Carbon::create('2020', '06', '1'),
        'status_id'        => 1,
        'is_overdue'       => 0,
        'late_completed'   => 0,
        'created_by'       => 2,
        'created_at'       => Carbon::create('2020', '01', '09'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 2,
        'assigned_to'      => 5,
        'name'             => 'Công việc của Vân 2',
        'description'      => 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr',
        'percent_complete' => 100,
        'start_date'       => Carbon::create('2020', '01', '12'),
        'due_on'           => Carbon::create('2020', '06', '1'),
        'status_id'        => 2,
        'is_overdue'       => 0,
        'late_completed'   => 1,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '01', '12'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 2,
        'assigned_to'      => 6,
        'name'             => 'Công việc của Linh 1',
        'description'      => '',
        'percent_complete' => 50,
        'start_date'       => Carbon::create('2020', '01', '14'),
        'due_on'           => Carbon::create('2020', '06', '1'),
        'status_id'        => 1,
        'is_overdue'       => 0,
        'late_completed'   => 0,
        'created_by'       => 3,
        'created_at'       => Carbon::create('2020', '01', '14'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 2,
        'assigned_to'      => 6,
        'name'             => 'Công việc của Linh 2',
        'description'      => '',
        'percent_complete' => 100,
        'start_date'       => Carbon::create('2020', '01', '20'),
        'due_on'           => Carbon::create('2020', '06', '1'),
        'status_id'        => 2,
        'is_overdue'       => 0,
        'late_completed'   => 0,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '01', '20'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 3,
        'assigned_to'      => 7,
        'name'             => 'Công việc của Hằng 1',
        'description'      => '',
        'percent_complete' => 30,
        'start_date'       => Carbon::create('2020', '01', '25'),
        'due_on'           => Carbon::create('2020', '06', '1'),
        'status_id'        => 1,
        'is_overdue'       => 0,
        'late_completed'   => 0,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '01', '25'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 3,
        'assigned_to'      => 7,
        'name'             => 'Công việc của Hằng 2',
        'description'      => '',
        'percent_complete' => 100,
        'start_date'       => Carbon::create('2020', '01', '22'),
        'due_on'           => Carbon::create('2020', '06', '1'),
        'status_id'        => 2,
        'is_overdue'       => 0,
        'late_completed'   => 1,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '01', '22'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 3,
        'assigned_to'      => 8,
        'name'             => 'Công việc của Tuyết 1',
        'description'      => '',
        'percent_complete' => 80,
        'start_date'       => Carbon::create('2020', '01', '27'),
        'due_on'           => Carbon::create('2020', '06', '1'),
        'status_id'        => 1,
        'is_overdue'       => 0,
        'late_completed'   => 0,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '01', '27'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 3,
        'assigned_to'      => 8,
        'name'             => 'Công việc của Tuyết 2',
        'description'      => '',
        'percent_complete' => 100,
        'start_date'       => Carbon::create('2020', '02', '03'),
        'due_on'           => Carbon::create('2020', '06', '1'),
        'status_id'        => 2,
        'is_overdue'       => 0,
        'late_completed'   => 0,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '02', '03'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 3,
        'assigned_to'      => 9,
        'name'             => 'Công việc của Mạnh 1',
        'description'      => '',
        'percent_complete' => 90,
        'start_date'       => Carbon::create('2020', '02', '10'),
        'due_on'           => Carbon::create('2020', '06', '1'),
        'status_id'        => 1,
        'is_overdue'       => 0,
        'late_completed'   => 0,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '02', '10'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 3,
        'assigned_to'      => 9,
        'name'             => 'Công việc của Mạnh 2',
        'description'      => '',
        'percent_complete' => 100,
        'start_date'       => Carbon::create('2020', '02', '12'),
        'due_on'           => Carbon::create('2020', '06', '1'),
        'status_id'        => 2,
        'is_overdue'       => 0,
        'late_completed'   => 1,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '02', '12'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 4,
        'assigned_to'      => 10,
        'name'             => 'Công việc của Thảo 1',
        'description'      => '',
        'percent_complete' => 20,
        'start_date'       => Carbon::create('2020', '02', '18'),
        'due_on'           => Carbon::create('2020', '06', '1'),
        'status_id'        => 1,
        'is_overdue'       => 0,
        'late_completed'   => 0,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '02', '18'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 4,
        'assigned_to'      => 10,
        'name'             => 'Công việc của Thảo 2',
        'description'      => '',
        'percent_complete' => 100,
        'start_date'       => Carbon::create('2020', '02', '24'),
        'due_on'           => Carbon::create('2020', '06', '1'),
        'status_id'        => 2,
        'is_overdue'       => 0,
        'late_completed'   => 1,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '02', '24'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 4,
        'assigned_to'      => 11,
        'name'             => 'Công việc của Phương 1',
        'description'      => '',
        'percent_complete' => 40,
        'start_date'       => Carbon::create('2020', '01', '12'),
        'due_on'           => Carbon::create('2020', '06', '1'),
        'status_id'        => 1,
        'is_overdue'       => 0,
        'late_completed'   => 0,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '01', '12'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 4,
        'assigned_to'      => 11,
        'name'             => 'Công việc của Phương 2',
        'description'      => '',
        'percent_complete' => 100,
        'start_date'       => Carbon::create('2020', '03', '2'),
        'due_on'           => Carbon::create('2020', '06', '1'),
        'status_id'        => 2,
        'is_overdue'       => 0,
        'late_completed'   => 0,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '03', '2'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 4,
        'assigned_to'      => 12,
        'name'             => 'Công việc của Huyền 1',
        'description'      => '',
        'percent_complete' => 30,
        'start_date'       => Carbon::create('2020', '03', '09'),
        'due_on'           => Carbon::create('2020', '06', '1'),
        'status_id'        => 1,
        'is_overdue'       => 0,
        'late_completed'   => 0,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '03', '09'),
        'updated_at'       => Carbon::now(),
      ],
      [
        'project_id'       => 4,
        'assigned_to'      => 12,
        'name'             => 'Công việc của Huyền 2',
        'description'      => '',
        'percent_complete' => 100,
        'start_date'       => Carbon::create('2020', '03', '12'),
        'due_on'           => Carbon::create('2020', '06', '1'),
        'status_id'        => 2,
        'is_overdue'       => 0,
        'late_completed'   => 1,
        'created_by'       => 1,
        'created_at'       => Carbon::create('2020', '03', '12'),
        'updated_at'       => Carbon::now(),
      ]
    ];

    DB::table('tasks')->insert($tasks);
  }
}
